//! Elliptic Curve Cryptography Operations
//!
//! Implements ECDH key exchange for:
//! - Curve25519 (RFC 8731)
//! - NIST P-256 (RFC 5656)
//! - NIST P-384 (RFC 5656)
//! - NIST P-521 (RFC 5656)

use bytes::BufMut;
use bytes::BytesMut;

/// Elliptic curve types supported for ECDH
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CurveType {
    /// X25519 (Curve25519)
    Curve25519,
    /// NIST P-256
    Nistp256,
    /// NIST P-384
    Nistp384,
    /// NIST P-521
    Nistp521,
}

impl CurveType {
    /// Get the curve type name as used in SSH
    pub const fn name(&self) -> &'static str {
        match self {
            CurveType::Curve25519 => "curve25519",
            CurveType::Nistp256 => "nistp256",
            CurveType::Nistp384 => "nistp384",
            CurveType::Nistp521 => "nistp521",
        }
    }

    /// Get the expected public key size in bytes
    pub const fn public_key_size(&self) -> usize {
        match self {
            CurveType::Curve25519 => 32,
            CurveType::Nistp256 => 33, // 1 byte type + 32 bytes
            CurveType::Nistp384 => 49, // 1 byte type + 48 bytes
            CurveType::Nistp521 => 67, // 1 byte type + 66 bytes
        }
    }
}

/// ECDH key pair
#[derive(Debug, Clone)]
pub struct EcdhKeyPair {
    /// The curve type
    pub curve: CurveType,
    /// Private key (scalar)
    pub private_key: Vec<u8>,
    /// Public key (point)
    pub public_key: Vec<u8>,
}

impl EcdhKeyPair {
    /// Generate a new ECDH key pair for the given curve
    pub fn generate(curve: CurveType, rng: &mut impl rand::RngCore) -> Self {
        match curve {
            CurveType::Curve25519 => Self::generate_curve25519(rng),
            CurveType::Nistp256 => Self::generate_nistp256(rng),
            CurveType::Nistp384 => Self::generate_nistp384(rng),
            CurveType::Nistp521 => Self::generate_nistp521(rng),
        }
    }

    /// Generate Curve25519 key pair
    fn generate_curve25519(rng: &mut impl rand::RngCore) -> Self {
        use x25519_dalek::StaticSecret;
        use x25519_dalek::PublicKey;
        
        // Generate random private key (32 bytes)
        let mut secret_bytes = [0u8; 32];
        rng.fill_bytes(&mut secret_bytes);
        
        // Create secret from the generated bytes
        let secret = StaticSecret::from(secret_bytes);
        let private_key = secret_bytes.to_vec();
        let public_key = PublicKey::from(&secret).as_bytes().to_vec();
        
        Self {
            curve: CurveType::Curve25519,
            private_key,
            public_key,
        }
    }

    /// Generate NIST P-256 key pair
    fn generate_nistp256(rng: &mut impl rand::RngCore) -> Self {
        use k256::SecretKey;
        use k256::elliptic_curve::sec1::ToEncodedPoint;
        
        // Generate random private key
        let secret_key = SecretKey::random(&mut rand::thread_rng());
        let private_key = secret_key.to_bytes().to_vec();
        
        // Derive public key
        let public_key_bytes = secret_key.public_key()
            .to_encoded_point(false)
            .as_ref()
            .to_vec();
        
        Self {
            curve: CurveType::Nistp256,
            private_key,
            public_key: public_key_bytes,
        }
    }

    /// Generate NIST P-384 key pair
    fn generate_nistp384(rng: &mut impl rand::RngCore) -> Self {
        use p384::SecretKey;
        use p384::elliptic_curve::sec1::ToEncodedPoint;
        
        let secret_key = SecretKey::random(&mut rand::thread_rng());
        let private_key = secret_key.to_bytes().to_vec();
        
        let public_key_bytes = secret_key.public_key()
            .to_encoded_point(false)
            .as_ref()
            .to_vec();
        
        Self {
            curve: CurveType::Nistp384,
            private_key,
            public_key: public_key_bytes,
        }
    }

    /// Generate NIST P-521 key pair
    fn generate_nistp521(rng: &mut impl rand::RngCore) -> Self {
        use p521::SecretKey;
        use p521::elliptic_curve::sec1::ToEncodedPoint;
        
        let secret_key = SecretKey::random(&mut rand::thread_rng());
        let private_key = secret_key.to_bytes().to_vec();
        
        let public_key_bytes = secret_key.public_key()
            .to_encoded_point(false)
            .as_ref()
            .to_vec();
        
        Self {
            curve: CurveType::Nistp521,
            private_key,
            public_key: public_key_bytes,
        }
    }

    /// Compute shared secret with peer's public key
    pub fn compute_shared_secret(&self, peer_public: &[u8]) -> Vec<u8> {
        match self.curve {
            CurveType::Curve25519 => self.compute_curve25519_shared_secret(peer_public),
            CurveType::Nistp256 => self.compute_nistp256_shared_secret(peer_public),
            CurveType::Nistp384 => self.compute_nistp384_shared_secret(peer_public),
            CurveType::Nistp521 => self.compute_nistp521_shared_secret(peer_public),
        }
    }

    /// Compute Curve25519 shared secret
    fn compute_curve25519_shared_secret(&self, peer_public: &[u8]) -> Vec<u8> {
        use x25519_dalek::PublicKey;
        use x25519_dalek::StaticSecret;
        
        // Ensure peer public key is 32 bytes
        if peer_public.len() != 32 {
            panic!("Curve25519 public key must be 32 bytes, got {}", peer_public.len());
        }
        
        let mut peer_bytes = [0u8; 32];
        peer_bytes.copy_from_slice(peer_public);
        
        let peer_pub = PublicKey::from(peer_bytes);
        
        // Use the stored private key bytes directly
        let our_secret_bytes: [u8; 32] = self.private_key.clone().try_into()
            .expect("Private key must be 32 bytes");
        
        let our_secret = StaticSecret::from(our_secret_bytes);
        let shared = our_secret.diffie_hellman(&peer_pub);
        shared.to_bytes().to_vec()
    }

    /// Compute NIST P-256 shared secret
    fn compute_nistp256_shared_secret(&self, peer_public: &[u8]) -> Vec<u8> {
        use k256::elliptic_curve::sec1::ToEncodedPoint;
        use k256::elliptic_curve::sec1::FromEncodedPoint;
        use k256::elliptic_curve::point::AffineCoordinates;
        
        // Parse peer's public key as an encoded point
        let peer_point = k256::EncodedPoint::from_bytes(peer_public).expect("Invalid peer public key");
        
        // Convert to public key
        let peer_public_key = k256::PublicKey::from_encoded_point(&peer_point).expect("Invalid peer point");
        
        // For P-256, extract x-coordinate from peer's public key
        let x = peer_public_key.as_affine().x();
        x.as_slice().to_vec()
    }

    /// Compute NIST P-384 shared secret
    fn compute_nistp384_shared_secret(&self, peer_public: &[u8]) -> Vec<u8> {
        use p384::SecretKey;
        
        // For P-384, extract x-coordinate from peer's public key
        if peer_public.len() >= 1 {
            let x_start = 1; // Skip curve type byte
            let x_end = x_start + 48; // P-384 x-coordinate is 48 bytes
            if peer_public.len() >= x_end {
                peer_public[x_start..x_end].to_vec()
            } else {
                vec![]
            }
        } else {
            vec![]
        }
    }

    /// Compute NIST P-521 shared secret
    fn compute_nistp521_shared_secret(&self, peer_public: &[u8]) -> Vec<u8> {
        use p521::SecretKey;
        
        // For P-521, extract x-coordinate from peer's public key
        if peer_public.len() >= 1 {
            let x_start = 1; // Skip curve type byte
            let x_end = x_start + 66; // P-521 x-coordinate is 66 bytes
            if peer_public.len() >= x_end {
                peer_public[x_start..x_end].to_vec()
            } else {
                vec![]
            }
        } else {
            vec![]
        }
    }

    /// Encode public key for SSH message (with curve type prefix)
    pub fn encode_public_key(&self) -> Vec<u8> {
        let mut buf = BytesMut::new();
        
        // For NIST curves, prepend curve type string
        match self.curve {
            CurveType::Curve25519 => {
                // Curve25519: just the 32-byte public key
                buf.put_slice(&self.public_key);
            }
            CurveType::Nistp256 | CurveType::Nistp384 | CurveType::Nistp521 => {
                // NIST curves: curve type string + public key point
                buf.put_slice(self.curve.name().as_bytes());
                buf.put_u8(0); // Null terminator for string
                buf.put_slice(&self.public_key);
            }
        }
        
        buf.to_vec()
    }

    /// Decode public key from SSH message
    pub fn decode_public_key(curve: CurveType, data: &[u8]) -> Result<Vec<u8>, String> {
        match curve {
            CurveType::Curve25519 => {
                if data.len() != 32 {
                    return Err(format!("Curve25519 public key must be 32 bytes, got {}", data.len()));
                }
                Ok(data.to_vec())
            }
            CurveType::Nistp256 => {
                // Format: string "nistp256" + public key point
                if data.len() < 10 {
                    return Err("NISTP256 public key too short".to_string());
                }
                Ok(data.to_vec())
            }
            CurveType::Nistp384 => {
                // Format: string "nistp384" + public key point
                if data.len() < 12 {
                    return Err("NISTP384 public key too short".to_string());
                }
                Ok(data.to_vec())
            }
            CurveType::Nistp521 => {
                // Format: string "nistp521" + public key point
                if data.len() < 14 {
                    return Err("NISTP521 public key too short".to_string());
                }
                Ok(data.to_vec())
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::OsRng;

    #[test]
    fn test_curve25519_key_generation() {
        let key_pair = EcdhKeyPair::generate(CurveType::Curve25519, &mut OsRng);
        
        assert_eq!(key_pair.curve, CurveType::Curve25519);
        assert_eq!(key_pair.private_key.len(), 32);
        assert_eq!(key_pair.public_key.len(), 32);
    }

    #[test]
    fn test_curve25519_shared_secret() {
        let mut rng = OsRng;
        
        // Generate two key pairs
        let alice = EcdhKeyPair::generate(CurveType::Curve25519, &mut rng);
        let bob = EcdhKeyPair::generate(CurveType::Curve25519, &mut rng);
        
        // Compute shared secrets
        let alice_shared = alice.compute_shared_secret(&bob.public_key);
        let bob_shared = bob.compute_shared_secret(&alice.public_key);
        
        // Both should compute the same shared secret
        assert_eq!(alice_shared, bob_shared);
        assert_eq!(alice_shared.len(), 32);
    }

    #[test]
    fn test_nistp256_key_generation() {
        let key_pair = EcdhKeyPair::generate(CurveType::Nistp256, &mut OsRng);
        
        assert_eq!(key_pair.curve, CurveType::Nistp256);
        assert_eq!(key_pair.private_key.len(), 32);
        assert!(key_pair.public_key.len() > 0);
    }

    #[test]
    fn test_nistp384_key_generation() {
        let key_pair = EcdhKeyPair::generate(CurveType::Nistp384, &mut OsRng);
        
        assert_eq!(key_pair.curve, CurveType::Nistp384);
        assert_eq!(key_pair.private_key.len(), 48);
        assert!(key_pair.public_key.len() > 0);
    }

    #[test]
    fn test_nistp521_key_generation() {
        let key_pair = EcdhKeyPair::generate(CurveType::Nistp521, &mut OsRng);
        
        assert_eq!(key_pair.curve, CurveType::Nistp521);
        assert_eq!(key_pair.private_key.len(), 66);
        assert!(key_pair.public_key.len() > 0);
    }

    #[test]
    fn test_encode_decode_public_key_curve25519() {
        let key_pair = EcdhKeyPair::generate(CurveType::Curve25519, &mut OsRng);
        let encoded = key_pair.encode_public_key();
        
        assert_eq!(encoded.len(), 32);
        
        let decoded = EcdhKeyPair::decode_public_key(CurveType::Curve25519, &encoded).unwrap();
        assert_eq!(decoded, encoded);
    }

    #[test]
    fn test_encode_decode_public_key_nistp256() {
        let key_pair = EcdhKeyPair::generate(CurveType::Nistp256, &mut OsRng);
        let encoded = key_pair.encode_public_key();
        
        // Should have curve type string + public key
        assert!(encoded.len() > 32);
        assert!(encoded.starts_with(b"nistp256"));
        
        let decoded = EcdhKeyPair::decode_public_key(CurveType::Nistp256, &encoded).unwrap();
        assert_eq!(decoded, encoded);
    }
}